### ISSUE TITLE
Rationale link not working

### ISSUE THREAD

**Issue by Nosferath** [CharlesGaydon/Fast-CMIM#1]
The link in the first bullet point ("For the rationale of this algorithm and of the fast implementation, see this webpage"), which is http://www.ams.jhu.edu/~yqin/cvrg/Feature_Selection.htm#ch1_2 is dead. Any other website where this information is available?

**Comment by CharlesGaydon** [comment]
Thanks for noticing. I found another reference and linked it in the Readme. Hope this will clarify things ! 
http://wiki.cvrgrid.org/index.php/FeatureSelection

**Comment by Nosferath** [comment]
That link also seems to be dead. I'm specifically looking for an explanation on the differences between this implementation and the one from `skfeature`.

**Comment by CharlesGaydon** [comment]
The link works fine on my end, and here is a screenshot of what I was referencing: 
![image](https://user-images.githubusercontent.com/11660435/92249972-241eee00-eecb-11ea-8a79-9a3ca22da22b.png).
In terms of difference betwen skfeature and this implementation, I suggest that you try to compare them by their pseudocode (cf. fast implementation pseudocode on the wiki.cvrgrid); the project is just too far in the past for me to remember the specifics.
